### ISSUE TITLE
Can't install sunode

### ISSUE THREAD

**Issue by cindyliuyn** [pymc-devs/sunode#43]
Hello,

I tried to install sunode but was stuck with solving environment step.  Could you have a look please? 

To reproduce: 
'''
conda config --add channels conda-forge
conda config --set channel_priority strict
conda install sunode
'''
Then I saw this in my terminal. It was stuck at solving environment and didn't manage to succeed. 
<img width="466" alt="Screenshot 2023-07-02 at 14 34 03" src="https://github.com/pymc-devs/sunode/assets/11205194/552964be-b91c-437b-b434-8a666abeb76b">

Thanks!

**Comment by maresb** [comment]
Hi @cindyliuyn, could you please retry using Mamba in Place of Conda?

https://GitHub.com/mamba-org/mamba

**Comment by michaelosthege** [comment]
Last week we pushed a new 0.5.0 release, also to conda-forge

👇 This now works, so I'm closing the issue

```
mamba create -n sundev -c conda-forge "sunode==0.5.0"
```

But feel free to report any problems!
